/*
 * generated by Xtext 2.35.0
 */
package ch.vobos.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TypescriptUiModule extends AbstractTypescriptUiModule {

	public TypescriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
