/**
 * generated by Xtext 2.35.0
 */
package jpadsl.jPADsl.impl;

import jpadsl.jPADsl.JPADslPackage;
import jpadsl.jPADsl.ManyToManyMappedByRelationshipAttribute;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Many To Many Mapped By Relationship Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ManyToManyMappedByRelationshipAttributeImpl extends MultipleRelationshipAttributeImpl implements ManyToManyMappedByRelationshipAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ManyToManyMappedByRelationshipAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JPADslPackage.Literals.MANY_TO_MANY_MAPPED_BY_RELATIONSHIP_ATTRIBUTE;
  }

} //ManyToManyMappedByRelationshipAttributeImpl
