/*
 * generated by Xtext 2.35.0
 */
package io.yaktor.ui.tests;

import com.google.inject.Injector;
import io.yaktor.domain.cs.ui.internal.CsActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DomainUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CsActivator.getInstance().getInjector("io.yaktor.Domain");
	}

}
