/**
 * generated by Xtext 2.35.0
 */
package jpaqldsl.jPAQLDsl.impl;

import jpaqldsl.jPAQLDsl.EmptyCollectionComparisonExpression;
import jpaqldsl.jPAQLDsl.JPAPathExpression;
import jpaqldsl.jPAQLDsl.JPAQLDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Empty Collection Comparison Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link jpaqldsl.jPAQLDsl.impl.EmptyCollectionComparisonExpressionImpl#getPathExpression <em>Path Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EmptyCollectionComparisonExpressionImpl extends MinimalEObjectImpl.Container implements EmptyCollectionComparisonExpression
{
  /**
   * The cached value of the '{@link #getPathExpression() <em>Path Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPathExpression()
   * @generated
   * @ordered
   */
  protected JPAPathExpression pathExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EmptyCollectionComparisonExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JPAQLDslPackage.Literals.EMPTY_COLLECTION_COMPARISON_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JPAPathExpression getPathExpression()
  {
    return pathExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPathExpression(JPAPathExpression newPathExpression, NotificationChain msgs)
  {
    JPAPathExpression oldPathExpression = pathExpression;
    pathExpression = newPathExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION, oldPathExpression, newPathExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPathExpression(JPAPathExpression newPathExpression)
  {
    if (newPathExpression != pathExpression)
    {
      NotificationChain msgs = null;
      if (pathExpression != null)
        msgs = ((InternalEObject)pathExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION, null, msgs);
      if (newPathExpression != null)
        msgs = ((InternalEObject)newPathExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION, null, msgs);
      msgs = basicSetPathExpression(newPathExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION, newPathExpression, newPathExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION:
        return basicSetPathExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION:
        return getPathExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION:
        setPathExpression((JPAPathExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION:
        setPathExpression((JPAPathExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.EMPTY_COLLECTION_COMPARISON_EXPRESSION__PATH_EXPRESSION:
        return pathExpression != null;
    }
    return super.eIsSet(featureID);
  }

} //EmptyCollectionComparisonExpressionImpl
