/**
 * generated by Xtext 2.35.0
 */
package jpaqldsl.jPAQLDsl.impl;

import jpaqldsl.jPAQLDsl.IdentificationVariable;
import jpaqldsl.jPAQLDsl.InputParameter;
import jpaqldsl.jPAQLDsl.JPAQLDslPackage;
import jpaqldsl.jPAQLDsl.SimpleEntityExpression;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Entity Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link jpaqldsl.jPAQLDsl.impl.SimpleEntityExpressionImpl#getIdentificationVariable <em>Identification Variable</em>}</li>
 *   <li>{@link jpaqldsl.jPAQLDsl.impl.SimpleEntityExpressionImpl#getInputParameter <em>Input Parameter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimpleEntityExpressionImpl extends MinimalEObjectImpl.Container implements SimpleEntityExpression
{
  /**
   * The cached value of the '{@link #getIdentificationVariable() <em>Identification Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentificationVariable()
   * @generated
   * @ordered
   */
  protected IdentificationVariable identificationVariable;

  /**
   * The cached value of the '{@link #getInputParameter() <em>Input Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputParameter()
   * @generated
   * @ordered
   */
  protected InputParameter inputParameter;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleEntityExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JPAQLDslPackage.Literals.SIMPLE_ENTITY_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IdentificationVariable getIdentificationVariable()
  {
    return identificationVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIdentificationVariable(IdentificationVariable newIdentificationVariable, NotificationChain msgs)
  {
    IdentificationVariable oldIdentificationVariable = identificationVariable;
    identificationVariable = newIdentificationVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE, oldIdentificationVariable, newIdentificationVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIdentificationVariable(IdentificationVariable newIdentificationVariable)
  {
    if (newIdentificationVariable != identificationVariable)
    {
      NotificationChain msgs = null;
      if (identificationVariable != null)
        msgs = ((InternalEObject)identificationVariable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE, null, msgs);
      if (newIdentificationVariable != null)
        msgs = ((InternalEObject)newIdentificationVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE, null, msgs);
      msgs = basicSetIdentificationVariable(newIdentificationVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE, newIdentificationVariable, newIdentificationVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputParameter getInputParameter()
  {
    return inputParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInputParameter(InputParameter newInputParameter, NotificationChain msgs)
  {
    InputParameter oldInputParameter = inputParameter;
    inputParameter = newInputParameter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER, oldInputParameter, newInputParameter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInputParameter(InputParameter newInputParameter)
  {
    if (newInputParameter != inputParameter)
    {
      NotificationChain msgs = null;
      if (inputParameter != null)
        msgs = ((InternalEObject)inputParameter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER, null, msgs);
      if (newInputParameter != null)
        msgs = ((InternalEObject)newInputParameter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER, null, msgs);
      msgs = basicSetInputParameter(newInputParameter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER, newInputParameter, newInputParameter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE:
        return basicSetIdentificationVariable(null, msgs);
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER:
        return basicSetInputParameter(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE:
        return getIdentificationVariable();
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER:
        return getInputParameter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE:
        setIdentificationVariable((IdentificationVariable)newValue);
        return;
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER:
        setInputParameter((InputParameter)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE:
        setIdentificationVariable((IdentificationVariable)null);
        return;
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER:
        setInputParameter((InputParameter)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__IDENTIFICATION_VARIABLE:
        return identificationVariable != null;
      case JPAQLDslPackage.SIMPLE_ENTITY_EXPRESSION__INPUT_PARAMETER:
        return inputParameter != null;
    }
    return super.eIsSet(featureID);
  }

} //SimpleEntityExpressionImpl
