/**
 * generated by Xtext 2.35.0
 */
package accessdsl.accessDsl;

import jpadsl.jPADsl.Entity;
import jpadsl.jPADsl.RelationshipAttribute;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Persist And Associate Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link accessdsl.accessDsl.PersistAndAssociateOperation#getNewEntity <em>New Entity</em>}</li>
 *   <li>{@link accessdsl.accessDsl.PersistAndAssociateOperation#getAssocialtion <em>Associaltion</em>}</li>
 *   <li>{@link accessdsl.accessDsl.PersistAndAssociateOperation#getExistingEntity <em>Existing Entity</em>}</li>
 * </ul>
 *
 * @see accessdsl.accessDsl.AccessDslPackage#getPersistAndAssociateOperation()
 * @model
 * @generated
 */
public interface PersistAndAssociateOperation extends StateOperation
{
  /**
   * Returns the value of the '<em><b>New Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Entity</em>' reference.
   * @see #setNewEntity(Entity)
   * @see accessdsl.accessDsl.AccessDslPackage#getPersistAndAssociateOperation_NewEntity()
   * @model
   * @generated
   */
  Entity getNewEntity();

  /**
   * Sets the value of the '{@link accessdsl.accessDsl.PersistAndAssociateOperation#getNewEntity <em>New Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Entity</em>' reference.
   * @see #getNewEntity()
   * @generated
   */
  void setNewEntity(Entity value);

  /**
   * Returns the value of the '<em><b>Associaltion</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Associaltion</em>' reference.
   * @see #setAssocialtion(RelationshipAttribute)
   * @see accessdsl.accessDsl.AccessDslPackage#getPersistAndAssociateOperation_Associaltion()
   * @model
   * @generated
   */
  RelationshipAttribute getAssocialtion();

  /**
   * Sets the value of the '{@link accessdsl.accessDsl.PersistAndAssociateOperation#getAssocialtion <em>Associaltion</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Associaltion</em>' reference.
   * @see #getAssocialtion()
   * @generated
   */
  void setAssocialtion(RelationshipAttribute value);

  /**
   * Returns the value of the '<em><b>Existing Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Existing Entity</em>' reference.
   * @see #setExistingEntity(Entity)
   * @see accessdsl.accessDsl.AccessDslPackage#getPersistAndAssociateOperation_ExistingEntity()
   * @model
   * @generated
   */
  Entity getExistingEntity();

  /**
   * Sets the value of the '{@link accessdsl.accessDsl.PersistAndAssociateOperation#getExistingEntity <em>Existing Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Existing Entity</em>' reference.
   * @see #getExistingEntity()
   * @generated
   */
  void setExistingEntity(Entity value);

} // PersistAndAssociateOperation
