/**
 * generated by Xtext 2.35.0
 */
package org.tvtower.db.database;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Achievements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tvtower.db.database.Achievements#getAchievements <em>Achievements</em>}</li>
 * </ul>
 *
 * @see org.tvtower.db.database.DatabasePackage#getAchievements()
 * @model
 * @generated
 */
public interface Achievements extends Definition
{
  /**
   * Returns the value of the '<em><b>Achievements</b></em>' containment reference list.
   * The list contents are of type {@link org.tvtower.db.database.Achievement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Achievements</em>' containment reference list.
   * @see org.tvtower.db.database.DatabasePackage#getAchievements_Achievements()
   * @model containment="true"
   * @generated
   */
  EList<Achievement> getAchievements();

} // Achievements
