/**
 * generated by Xtext 2.35.0
 */
package org.tvtower.db.database;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Achievement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tvtower.db.database.Achievement#getName <em>Name</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getComment <em>Comment</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getCreator <em>Creator</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getCreatedBy <em>Created By</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getTitle <em>Title</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getText <em>Text</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getTasks <em>Tasks</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getRewards <em>Rewards</em>}</li>
 *   <li>{@link org.tvtower.db.database.Achievement#getData <em>Data</em>}</li>
 * </ul>
 *
 * @see org.tvtower.db.database.DatabasePackage#getAchievement()
 * @model
 * @generated
 */
public interface Achievement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

  /**
   * Returns the value of the '<em><b>Creator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Creator</em>' attribute.
   * @see #setCreator(String)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Creator()
   * @model
   * @generated
   */
  String getCreator();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getCreator <em>Creator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Creator</em>' attribute.
   * @see #getCreator()
   * @generated
   */
  void setCreator(String value);

  /**
   * Returns the value of the '<em><b>Created By</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Created By</em>' attribute.
   * @see #setCreatedBy(String)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_CreatedBy()
   * @model
   * @generated
   */
  String getCreatedBy();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getCreatedBy <em>Created By</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Created By</em>' attribute.
   * @see #getCreatedBy()
   * @generated
   */
  void setCreatedBy(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(Title)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Title()
   * @model containment="true"
   * @generated
   */
  Title getTitle();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Title value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(Text)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Text()
   * @model containment="true"
   * @generated
   */
  Text getText();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(Text value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference.
   * @see #setTasks(Tasks)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Tasks()
   * @model containment="true"
   * @generated
   */
  Tasks getTasks();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getTasks <em>Tasks</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tasks</em>' containment reference.
   * @see #getTasks()
   * @generated
   */
  void setTasks(Tasks value);

  /**
   * Returns the value of the '<em><b>Rewards</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rewards</em>' containment reference.
   * @see #setRewards(Rewards)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Rewards()
   * @model containment="true"
   * @generated
   */
  Rewards getRewards();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getRewards <em>Rewards</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rewards</em>' containment reference.
   * @see #getRewards()
   * @generated
   */
  void setRewards(Rewards value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference.
   * @see #setData(AchievementData)
   * @see org.tvtower.db.database.DatabasePackage#getAchievement_Data()
   * @model containment="true"
   * @generated
   */
  AchievementData getData();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.Achievement#getData <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' containment reference.
   * @see #getData()
   * @generated
   */
  void setData(AchievementData value);

} // Achievement
