/**
 * generated by Xtext 2.35.0
 */
package org.tvtower.db.database;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Advertisement Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getQuality <em>Quality</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getAvailable <em>Available</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getType <em>Type</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getRepetitions <em>Repetitions</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getProfit <em>Profit</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getFixPrice <em>Fix Price</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getPenalty <em>Penalty</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getInfomercial <em>Infomercial</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getBlocks <em>Blocks</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getInfomercialProfit <em>Infomercial Profit</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getFixInfomercialProfit <em>Fix Infomercial Profit</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getProPressureGroup <em>Pro Pressure Group</em>}</li>
 *   <li>{@link org.tvtower.db.database.AdvertisementData#getContraPressureGroup <em>Contra Pressure Group</em>}</li>
 * </ul>
 *
 * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData()
 * @model
 * @generated
 */
public interface AdvertisementData extends EObject
{
  /**
   * Returns the value of the '<em><b>Quality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quality</em>' attribute.
   * @see #setQuality(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Quality()
   * @model
   * @generated
   */
  String getQuality();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getQuality <em>Quality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quality</em>' attribute.
   * @see #getQuality()
   * @generated
   */
  void setQuality(String value);

  /**
   * Returns the value of the '<em><b>Available</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Available</em>' attribute.
   * @see #setAvailable(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Available()
   * @model
   * @generated
   */
  String getAvailable();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getAvailable <em>Available</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Available</em>' attribute.
   * @see #getAvailable()
   * @generated
   */
  void setAvailable(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Repetitions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repetitions</em>' attribute.
   * @see #setRepetitions(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Repetitions()
   * @model
   * @generated
   */
  String getRepetitions();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getRepetitions <em>Repetitions</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repetitions</em>' attribute.
   * @see #getRepetitions()
   * @generated
   */
  void setRepetitions(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Duration()
   * @model
   * @generated
   */
  String getDuration();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(String value);

  /**
   * Returns the value of the '<em><b>Profit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Profit</em>' attribute.
   * @see #setProfit(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Profit()
   * @model
   * @generated
   */
  String getProfit();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getProfit <em>Profit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Profit</em>' attribute.
   * @see #getProfit()
   * @generated
   */
  void setProfit(String value);

  /**
   * Returns the value of the '<em><b>Fix Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fix Price</em>' attribute.
   * @see #setFixPrice(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_FixPrice()
   * @model
   * @generated
   */
  String getFixPrice();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getFixPrice <em>Fix Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fix Price</em>' attribute.
   * @see #getFixPrice()
   * @generated
   */
  void setFixPrice(String value);

  /**
   * Returns the value of the '<em><b>Penalty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Penalty</em>' attribute.
   * @see #setPenalty(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Penalty()
   * @model
   * @generated
   */
  String getPenalty();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getPenalty <em>Penalty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Penalty</em>' attribute.
   * @see #getPenalty()
   * @generated
   */
  void setPenalty(String value);

  /**
   * Returns the value of the '<em><b>Infomercial</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infomercial</em>' attribute.
   * @see #setInfomercial(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Infomercial()
   * @model
   * @generated
   */
  String getInfomercial();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getInfomercial <em>Infomercial</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Infomercial</em>' attribute.
   * @see #getInfomercial()
   * @generated
   */
  void setInfomercial(String value);

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' attribute.
   * @see #setBlocks(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_Blocks()
   * @model
   * @generated
   */
  String getBlocks();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getBlocks <em>Blocks</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Blocks</em>' attribute.
   * @see #getBlocks()
   * @generated
   */
  void setBlocks(String value);

  /**
   * Returns the value of the '<em><b>Infomercial Profit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infomercial Profit</em>' attribute.
   * @see #setInfomercialProfit(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_InfomercialProfit()
   * @model
   * @generated
   */
  String getInfomercialProfit();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getInfomercialProfit <em>Infomercial Profit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Infomercial Profit</em>' attribute.
   * @see #getInfomercialProfit()
   * @generated
   */
  void setInfomercialProfit(String value);

  /**
   * Returns the value of the '<em><b>Fix Infomercial Profit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fix Infomercial Profit</em>' attribute.
   * @see #setFixInfomercialProfit(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_FixInfomercialProfit()
   * @model
   * @generated
   */
  String getFixInfomercialProfit();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getFixInfomercialProfit <em>Fix Infomercial Profit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fix Infomercial Profit</em>' attribute.
   * @see #getFixInfomercialProfit()
   * @generated
   */
  void setFixInfomercialProfit(String value);

  /**
   * Returns the value of the '<em><b>Pro Pressure Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pro Pressure Group</em>' attribute.
   * @see #setProPressureGroup(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_ProPressureGroup()
   * @model
   * @generated
   */
  String getProPressureGroup();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getProPressureGroup <em>Pro Pressure Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pro Pressure Group</em>' attribute.
   * @see #getProPressureGroup()
   * @generated
   */
  void setProPressureGroup(String value);

  /**
   * Returns the value of the '<em><b>Contra Pressure Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contra Pressure Group</em>' attribute.
   * @see #setContraPressureGroup(String)
   * @see org.tvtower.db.database.DatabasePackage#getAdvertisementData_ContraPressureGroup()
   * @model
   * @generated
   */
  String getContraPressureGroup();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.AdvertisementData#getContraPressureGroup <em>Contra Pressure Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contra Pressure Group</em>' attribute.
   * @see #getContraPressureGroup()
   * @generated
   */
  void setContraPressureGroup(String value);

} // AdvertisementData
