/**
 * generated by Xtext 2.35.0
 */
package org.tvtower.db.database;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Script Genres</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.tvtower.db.database.ScriptGenres#getMainGenre <em>Main Genre</em>}</li>
 *   <li>{@link org.tvtower.db.database.ScriptGenres#getSubgenres <em>Subgenres</em>}</li>
 * </ul>
 *
 * @see org.tvtower.db.database.DatabasePackage#getScriptGenres()
 * @model
 * @generated
 */
public interface ScriptGenres extends EObject
{
  /**
   * Returns the value of the '<em><b>Main Genre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Genre</em>' attribute.
   * @see #setMainGenre(String)
   * @see org.tvtower.db.database.DatabasePackage#getScriptGenres_MainGenre()
   * @model
   * @generated
   */
  String getMainGenre();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.ScriptGenres#getMainGenre <em>Main Genre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main Genre</em>' attribute.
   * @see #getMainGenre()
   * @generated
   */
  void setMainGenre(String value);

  /**
   * Returns the value of the '<em><b>Subgenres</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subgenres</em>' attribute.
   * @see #setSubgenres(String)
   * @see org.tvtower.db.database.DatabasePackage#getScriptGenres_Subgenres()
   * @model
   * @generated
   */
  String getSubgenres();

  /**
   * Sets the value of the '{@link org.tvtower.db.database.ScriptGenres#getSubgenres <em>Subgenres</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subgenres</em>' attribute.
   * @see #getSubgenres()
   * @generated
   */
  void setSubgenres(String value);

} // ScriptGenres
