/**
 * generated by Xtext 2.35.0
 */
package accessdsl.accessDsl.impl;

import accessdsl.accessDsl.AccessDslPackage;
import accessdsl.accessDsl.Import;
import accessdsl.accessDsl.StateAdjustment;
import accessdsl.accessDsl.StateOperation;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>State Adjustment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link accessdsl.accessDsl.impl.StateAdjustmentImpl#getName <em>Name</em>}</li>
 *   <li>{@link accessdsl.accessDsl.impl.StateAdjustmentImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link accessdsl.accessDsl.impl.StateAdjustmentImpl#getStateOperation <em>State Operation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StateAdjustmentImpl extends MinimalEObjectImpl.Container implements StateAdjustment
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<Import> imports;

  /**
   * The cached value of the '{@link #getStateOperation() <em>State Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStateOperation()
   * @generated
   * @ordered
   */
  protected StateOperation stateOperation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StateAdjustmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AccessDslPackage.Literals.STATE_ADJUSTMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AccessDslPackage.STATE_ADJUSTMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Import> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<Import>(Import.class, this, AccessDslPackage.STATE_ADJUSTMENT__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StateOperation getStateOperation()
  {
    return stateOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStateOperation(StateOperation newStateOperation, NotificationChain msgs)
  {
    StateOperation oldStateOperation = stateOperation;
    stateOperation = newStateOperation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION, oldStateOperation, newStateOperation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStateOperation(StateOperation newStateOperation)
  {
    if (newStateOperation != stateOperation)
    {
      NotificationChain msgs = null;
      if (stateOperation != null)
        msgs = ((InternalEObject)stateOperation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION, null, msgs);
      if (newStateOperation != null)
        msgs = ((InternalEObject)newStateOperation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION, null, msgs);
      msgs = basicSetStateOperation(newStateOperation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION, newStateOperation, newStateOperation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AccessDslPackage.STATE_ADJUSTMENT__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION:
        return basicSetStateOperation(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AccessDslPackage.STATE_ADJUSTMENT__NAME:
        return getName();
      case AccessDslPackage.STATE_ADJUSTMENT__IMPORTS:
        return getImports();
      case AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION:
        return getStateOperation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AccessDslPackage.STATE_ADJUSTMENT__NAME:
        setName((String)newValue);
        return;
      case AccessDslPackage.STATE_ADJUSTMENT__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends Import>)newValue);
        return;
      case AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION:
        setStateOperation((StateOperation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AccessDslPackage.STATE_ADJUSTMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AccessDslPackage.STATE_ADJUSTMENT__IMPORTS:
        getImports().clear();
        return;
      case AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION:
        setStateOperation((StateOperation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AccessDslPackage.STATE_ADJUSTMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AccessDslPackage.STATE_ADJUSTMENT__IMPORTS:
        return imports != null && !imports.isEmpty();
      case AccessDslPackage.STATE_ADJUSTMENT__STATE_OPERATION:
        return stateOperation != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //StateAdjustmentImpl
