/*
 * generated by Xtext 2.35.0
 */
package de.sos.etj.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractETJValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.sos.etj.eTJ.ETJPackage.eINSTANCE);
		return result;
	}
}
