/**
 * generated by Xtext 2.35.0
 */
package yang.manager.yang.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import yang.manager.yang.WhenSubstatements;
import yang.manager.yang.YangPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>When Substatements</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WhenSubstatementsImpl extends MinimalEObjectImpl.Container implements WhenSubstatements
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WhenSubstatementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YangPackage.eINSTANCE.getWhenSubstatements();
  }

} //WhenSubstatementsImpl
