/**
 * generated by Xtext 2.35.0
 */
package workflowdsl.workflowDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflowdsl.workflowDsl.OutputData#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see workflowdsl.workflowDsl.WorkflowDslPackage#getOutputData()
 * @model
 * @generated
 */
public interface OutputData extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(StringBasedConditionalVaraible)
   * @see workflowdsl.workflowDsl.WorkflowDslPackage#getOutputData_Value()
   * @model
   * @generated
   */
  StringBasedConditionalVaraible getValue();

  /**
   * Sets the value of the '{@link workflowdsl.workflowDsl.OutputData#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(StringBasedConditionalVaraible value);

} // OutputData
