/**
 * generated by Xtext 2.35.0
 */
package jpadsl.jPADsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Internal Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jpadsl.jPADsl.JPADslPackage#getInternalAttribute()
 * @model
 * @generated
 */
public interface InternalAttribute extends Attribute
{
} // InternalAttribute
