/**
 * generated by Xtext 2.35.0
 */
package jpadsl.jPADsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Many To Many Mapped By Relationship Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jpadsl.jPADsl.JPADslPackage#getManyToManyMappedByRelationshipAttribute()
 * @model
 * @generated
 */
public interface ManyToManyMappedByRelationshipAttribute extends MultipleRelationshipAttribute
{
} // ManyToManyMappedByRelationshipAttribute
