/**
 * generated by Xtext 2.35.0
 */
package jpadsl.jPADsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Many To One Join Column Relation Ship Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jpadsl.jPADsl.ManyToOneJoinColumnRelationShipAttribute#getJoinColumnOverride <em>Join Column Override</em>}</li>
 * </ul>
 *
 * @see jpadsl.jPADsl.JPADslPackage#getManyToOneJoinColumnRelationShipAttribute()
 * @model
 * @generated
 */
public interface ManyToOneJoinColumnRelationShipAttribute extends SingularRelationshipAttribute
{
  /**
   * Returns the value of the '<em><b>Join Column Override</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Join Column Override</em>' attribute.
   * @see #setJoinColumnOverride(String)
   * @see jpadsl.jPADsl.JPADslPackage#getManyToOneJoinColumnRelationShipAttribute_JoinColumnOverride()
   * @model
   * @generated
   */
  String getJoinColumnOverride();

  /**
   * Sets the value of the '{@link jpadsl.jPADsl.ManyToOneJoinColumnRelationShipAttribute#getJoinColumnOverride <em>Join Column Override</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Join Column Override</em>' attribute.
   * @see #getJoinColumnOverride()
   * @generated
   */
  void setJoinColumnOverride(String value);

} // ManyToOneJoinColumnRelationShipAttribute
