/**
 * generated by Xtext 2.35.0
 */
package jpadsl.jPADsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Structural Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jpadsl.jPADsl.JPADslPackage#getStructuralFeature()
 * @model
 * @generated
 */
public interface StructuralFeature extends Feature
{
} // StructuralFeature
