/**
 * generated by Xtext 2.35.0
 */
package ch.vobos.typescript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ch.vobos.typescript.Declaration#getDocComment <em>Doc Comment</em>}</li>
 *   <li>{@link ch.vobos.typescript.Declaration#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @see ch.vobos.typescript.TypescriptPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Doc Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc Comment</em>' containment reference.
   * @see #setDocComment(DocComment)
   * @see ch.vobos.typescript.TypescriptPackage#getDeclaration_DocComment()
   * @model containment="true"
   * @generated
   */
  DocComment getDocComment();

  /**
   * Sets the value of the '{@link ch.vobos.typescript.Declaration#getDocComment <em>Doc Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc Comment</em>' containment reference.
   * @see #getDocComment()
   * @generated
   */
  void setDocComment(DocComment value);

  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(InterfaceOrClassDeclaration)
   * @see ch.vobos.typescript.TypescriptPackage#getDeclaration_Declaration()
   * @model containment="true"
   * @generated
   */
  InterfaceOrClassDeclaration getDeclaration();

  /**
   * Sets the value of the '{@link ch.vobos.typescript.Declaration#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(InterfaceOrClassDeclaration value);

} // Declaration
