/**
 * generated by Xtext 2.35.0
 */
package ch.vobos.typescript;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Doc Comment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ch.vobos.typescript.DocComment#getLines <em>Lines</em>}</li>
 *   <li>{@link ch.vobos.typescript.DocComment#getAnnotations <em>Annotations</em>}</li>
 * </ul>
 *
 * @see ch.vobos.typescript.TypescriptPackage#getDocComment()
 * @model
 * @generated
 */
public interface DocComment extends EObject
{
  /**
   * Returns the value of the '<em><b>Lines</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lines</em>' attribute list.
   * @see ch.vobos.typescript.TypescriptPackage#getDocComment_Lines()
   * @model unique="false"
   * @generated
   */
  EList<String> getLines();

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link ch.vobos.typescript.AnnotationLine}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see ch.vobos.typescript.TypescriptPackage#getDocComment_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<AnnotationLine> getAnnotations();

} // DocComment
