/**
 * generated by Xtext 2.35.0
 */
package ch.vobos.typescript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ch.vobos.typescript.ModuleElement#isExported <em>Exported</em>}</li>
 *   <li>{@link ch.vobos.typescript.ModuleElement#getModuleContent <em>Module Content</em>}</li>
 * </ul>
 *
 * @see ch.vobos.typescript.TypescriptPackage#getModuleElement()
 * @model
 * @generated
 */
public interface ModuleElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Exported</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exported</em>' attribute.
   * @see #setExported(boolean)
   * @see ch.vobos.typescript.TypescriptPackage#getModuleElement_Exported()
   * @model
   * @generated
   */
  boolean isExported();

  /**
   * Sets the value of the '{@link ch.vobos.typescript.ModuleElement#isExported <em>Exported</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exported</em>' attribute.
   * @see #isExported()
   * @generated
   */
  void setExported(boolean value);

  /**
   * Returns the value of the '<em><b>Module Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module Content</em>' containment reference.
   * @see #setModuleContent(EObject)
   * @see ch.vobos.typescript.TypescriptPackage#getModuleElement_ModuleContent()
   * @model containment="true"
   * @generated
   */
  EObject getModuleContent();

  /**
   * Sets the value of the '{@link ch.vobos.typescript.ModuleElement#getModuleContent <em>Module Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module Content</em>' containment reference.
   * @see #getModuleContent()
   * @generated
   */
  void setModuleContent(EObject value);

} // ModuleElement
