/**
 * generated by Xtext 2.35.0
 */
package ch.vobos.typescript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ch.vobos.typescript.TypescriptPackage#getTypeLiteral()
 * @model
 * @generated
 */
public interface TypeLiteral extends Type
{
} // TypeLiteral
