/**
 * generated by Xtext 2.35.0
 */
package dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.impl;

import dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.NowhereBycicleDslPackage;
import dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.PedalTypes;
import dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Pedals;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pedals</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.impl.PedalsImpl#getPedalType <em>Pedal Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PedalsImpl extends PartImpl implements Pedals
{
  /**
   * The default value of the '{@link #getPedalType() <em>Pedal Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPedalType()
   * @generated
   * @ordered
   */
  protected static final PedalTypes PEDAL_TYPE_EDEFAULT = PedalTypes.CHILD_PEDALS;

  /**
   * The cached value of the '{@link #getPedalType() <em>Pedal Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPedalType()
   * @generated
   * @ordered
   */
  protected PedalTypes pedalType = PEDAL_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PedalsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NowhereBycicleDslPackage.Literals.PEDALS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PedalTypes getPedalType()
  {
    return pedalType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPedalType(PedalTypes newPedalType)
  {
    PedalTypes oldPedalType = pedalType;
    pedalType = newPedalType == null ? PEDAL_TYPE_EDEFAULT : newPedalType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NowhereBycicleDslPackage.PEDALS__PEDAL_TYPE, oldPedalType, pedalType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NowhereBycicleDslPackage.PEDALS__PEDAL_TYPE:
        return getPedalType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NowhereBycicleDslPackage.PEDALS__PEDAL_TYPE:
        setPedalType((PedalTypes)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NowhereBycicleDslPackage.PEDALS__PEDAL_TYPE:
        setPedalType(PEDAL_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NowhereBycicleDslPackage.PEDALS__PEDAL_TYPE:
        return pedalType != PEDAL_TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (pedalType: ");
    result.append(pedalType);
    result.append(')');
    return result.toString();
  }

} //PedalsImpl
