/**
 * generated by Xtext 2.35.0
 */
package yang.manager.yang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Substatement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see yang.manager.yang.YangPackage#getInputSubstatement()
 * @model
 * @generated
 */
public interface InputSubstatement extends EObject
{
} // InputSubstatement
