/*
 * generated by Xtext 2.35.0
 */
package de.beyondjava.xtext.jsf.ui;

import com.google.inject.Injector;
import de.beyondjava.xtext.jsf.ui.internal.JsfActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ComponentLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JsfActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JsfActivator activator = JsfActivator.getInstance();
		return activator != null ? activator.getInjector(JsfActivator.DE_BEYONDJAVA_XTEXT_JSF_COMPONENTLANGUAGE) : null;
	}

}
