/*
 * generated by Xtext 2.35.0
 */
package accessdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AccessDslRuntimeModule extends AbstractAccessDslRuntimeModule {
}
