/*
 * generated by Xtext 2.35.0
 */
package de.altimos.mdsd.majordomo.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MajordomoDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/altimos/mdsd/majordomo/dsl/parser/antlr/internal/InternalMajordomoDsl.tokens");
	}
}
