/**
 * generated by Xtext 2.35.0
 */
package de.sos.etj.eTJ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complete</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.etj.eTJ.Complete#getComplete <em>Complete</em>}</li>
 * </ul>
 *
 * @see de.sos.etj.eTJ.ETJPackage#getComplete()
 * @model
 * @generated
 */
public interface Complete extends EObject
{
  /**
   * Returns the value of the '<em><b>Complete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complete</em>' attribute.
   * @see #setComplete(float)
   * @see de.sos.etj.eTJ.ETJPackage#getComplete_Complete()
   * @model
   * @generated
   */
  float getComplete();

  /**
   * Sets the value of the '{@link de.sos.etj.eTJ.Complete#getComplete <em>Complete</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complete</em>' attribute.
   * @see #getComplete()
   * @generated
   */
  void setComplete(float value);

} // Complete
