/**
 * generated by Xtext 2.35.0
 */
package de.sos.etj.eTJ;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Currency Format</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sos.etj.eTJ.ETJPackage#getCurrencyFormat()
 * @model
 * @generated
 */
public interface CurrencyFormat extends ProjectAttribute, ReportAttribute
{
} // CurrencyFormat
