/**
 * generated by Xtext 2.35.0
 */
package de.sos.etj.eTJ;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Daily Min</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sos.etj.eTJ.ETJPackage#getDailyMin()
 * @model
 * @generated
 */
public interface DailyMin extends LimitsAttribute
{
} // DailyMin
