/**
 * generated by Xtext 2.35.0
 */
package de.sos.etj.eTJ;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sort Tasks</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sos.etj.eTJ.ETJPackage#getSortTasks()
 * @model
 * @generated
 */
public interface SortTasks extends ReportAttribute, StatusSheetReportAttribute
{
} // SortTasks
