/**
 * generated by Xtext 2.35.0
 */
package nl.tue.ele.es.sdf3.editor.sDF3;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tue.ele.es.sdf3.editor.sDF3.Actor#getName <em>Name</em>}</li>
 *   <li>{@link nl.tue.ele.es.sdf3.editor.sDF3.Actor#getType <em>Type</em>}</li>
 *   <li>{@link nl.tue.ele.es.sdf3.editor.sDF3.Actor#getPorts <em>Ports</em>}</li>
 * </ul>
 *
 * @see nl.tue.ele.es.sdf3.editor.sDF3.SDF3Package#getActor()
 * @model
 * @generated
 */
public interface Actor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see nl.tue.ele.es.sdf3.editor.sDF3.SDF3Package#getActor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link nl.tue.ele.es.sdf3.editor.sDF3.Actor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see nl.tue.ele.es.sdf3.editor.sDF3.SDF3Package#getActor_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link nl.tue.ele.es.sdf3.editor.sDF3.Actor#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Ports</b></em>' containment reference list.
   * The list contents are of type {@link nl.tue.ele.es.sdf3.editor.sDF3.Port}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' containment reference list.
   * @see nl.tue.ele.es.sdf3.editor.sDF3.SDF3Package#getActor_Ports()
   * @model containment="true"
   * @generated
   */
  EList<Port> getPorts();

} // Actor
