/**
 * generated by Xtext 2.35.0
 */
package org.tvtower.db.database.impl;

import org.eclipse.emf.ecore.EClass;

import org.tvtower.db.database.DatabasePackage;
import org.tvtower.db.database.Episodes;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Episodes</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EpisodesImpl extends ContainsMinMaxSlopeImpl implements Episodes
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EpisodesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DatabasePackage.Literals.EPISODES;
  }

} //EpisodesImpl
