/**
 * generated by Xtext 2.35.0
 */
package org.tvtower.db.database.impl;

import org.eclipse.emf.ecore.EClass;

import org.tvtower.db.database.DatabasePackage;
import org.tvtower.db.database.Potential;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Potential</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PotentialImpl extends ContainsMinMaxSlopeImpl implements Potential
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PotentialImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DatabasePackage.Literals.POTENTIAL;
  }

} //PotentialImpl
