/*
 * generated by Xtext 2.35.0
 */
package org.eclipse.scout.saml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.scout.saml.SamlRuntimeModule;
import org.eclipse.scout.saml.SamlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SamlIdeSetup extends SamlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SamlRuntimeModule(), new SamlIdeModule()));
	}
	
}
