/**
 * generated by Xtext 2.35.0
 */
package dk.itu.mdd.nbs.dsl.nowhereBycicleDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frame</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Frame#getFrameType <em>Frame Type</em>}</li>
 *   <li>{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Frame#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.NowhereBycicleDslPackage#getFrame()
 * @model
 * @generated
 */
public interface Frame extends Part
{
  /**
   * Returns the value of the '<em><b>Frame Type</b></em>' attribute.
   * The literals are from the enumeration {@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.FrameType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frame Type</em>' attribute.
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.FrameType
   * @see #setFrameType(FrameType)
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.NowhereBycicleDslPackage#getFrame_FrameType()
   * @model
   * @generated
   */
  FrameType getFrameType();

  /**
   * Sets the value of the '{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Frame#getFrameType <em>Frame Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frame Type</em>' attribute.
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.FrameType
   * @see #getFrameType()
   * @generated
   */
  void setFrameType(FrameType value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Color}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Color
   * @see #setColor(Color)
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.NowhereBycicleDslPackage#getFrame_Color()
   * @model
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Frame#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Color
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

} // Frame
