/**
 * generated by Xtext 2.35.0
 */
package dk.itu.mdd.nbs.dsl.nowhereBycicleDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Saddle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Saddle#getSaddleType <em>Saddle Type</em>}</li>
 * </ul>
 *
 * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.NowhereBycicleDslPackage#getSaddle()
 * @model
 * @generated
 */
public interface Saddle extends Part
{
  /**
   * Returns the value of the '<em><b>Saddle Type</b></em>' attribute.
   * The literals are from the enumeration {@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.SaddleType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Saddle Type</em>' attribute.
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.SaddleType
   * @see #setSaddleType(SaddleType)
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.NowhereBycicleDslPackage#getSaddle_SaddleType()
   * @model
   * @generated
   */
  SaddleType getSaddleType();

  /**
   * Sets the value of the '{@link dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.Saddle#getSaddleType <em>Saddle Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Saddle Type</em>' attribute.
   * @see dk.itu.mdd.nbs.dsl.nowhereBycicleDsl.SaddleType
   * @see #getSaddleType()
   * @generated
   */
  void setSaddleType(SaddleType value);

} // Saddle
