/**
 * generated by Xtext 2.35.0
 */
package jpaqldsl.jPAQLDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arithmetic Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getArithmeticTerm()
 * @model
 * @generated
 */
public interface ArithmeticTerm extends Expression
{
} // ArithmeticTerm
