/**
 * generated by Xtext 2.35.0
 */
package jpaqldsl.jPAQLDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jpaqldsl.jPAQLDsl.EnumPrimary#getPathExpression <em>Path Expression</em>}</li>
 *   <li>{@link jpaqldsl.jPAQLDsl.EnumPrimary#getEnumLiteral <em>Enum Literal</em>}</li>
 *   <li>{@link jpaqldsl.jPAQLDsl.EnumPrimary#getInputParameter <em>Input Parameter</em>}</li>
 * </ul>
 *
 * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getEnumPrimary()
 * @model
 * @generated
 */
public interface EnumPrimary extends EObject
{
  /**
   * Returns the value of the '<em><b>Path Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Expression</em>' containment reference.
   * @see #setPathExpression(JPAPathExpression)
   * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getEnumPrimary_PathExpression()
   * @model containment="true"
   * @generated
   */
  JPAPathExpression getPathExpression();

  /**
   * Sets the value of the '{@link jpaqldsl.jPAQLDsl.EnumPrimary#getPathExpression <em>Path Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path Expression</em>' containment reference.
   * @see #getPathExpression()
   * @generated
   */
  void setPathExpression(JPAPathExpression value);

  /**
   * Returns the value of the '<em><b>Enum Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Literal</em>' containment reference.
   * @see #setEnumLiteral(EnumLiteral)
   * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getEnumPrimary_EnumLiteral()
   * @model containment="true"
   * @generated
   */
  EnumLiteral getEnumLiteral();

  /**
   * Sets the value of the '{@link jpaqldsl.jPAQLDsl.EnumPrimary#getEnumLiteral <em>Enum Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Literal</em>' containment reference.
   * @see #getEnumLiteral()
   * @generated
   */
  void setEnumLiteral(EnumLiteral value);

  /**
   * Returns the value of the '<em><b>Input Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Parameter</em>' containment reference.
   * @see #setInputParameter(InputParameter)
   * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getEnumPrimary_InputParameter()
   * @model containment="true"
   * @generated
   */
  InputParameter getInputParameter();

  /**
   * Sets the value of the '{@link jpaqldsl.jPAQLDsl.EnumPrimary#getInputParameter <em>Input Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Parameter</em>' containment reference.
   * @see #getInputParameter()
   * @generated
   */
  void setInputParameter(InputParameter value);

} // EnumPrimary
