/**
 * generated by Xtext 2.35.0
 */
package jpaqldsl.jPAQLDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link jpaqldsl.jPAQLDsl.StringExpression#getStringPrimary <em>String Primary</em>}</li>
 *   <li>{@link jpaqldsl.jPAQLDsl.StringExpression#getSubQuery <em>Sub Query</em>}</li>
 * </ul>
 *
 * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getStringExpression()
 * @model
 * @generated
 */
public interface StringExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>String Primary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Primary</em>' containment reference.
   * @see #setStringPrimary(StringPrimary)
   * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getStringExpression_StringPrimary()
   * @model containment="true"
   * @generated
   */
  StringPrimary getStringPrimary();

  /**
   * Sets the value of the '{@link jpaqldsl.jPAQLDsl.StringExpression#getStringPrimary <em>String Primary</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Primary</em>' containment reference.
   * @see #getStringPrimary()
   * @generated
   */
  void setStringPrimary(StringPrimary value);

  /**
   * Returns the value of the '<em><b>Sub Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Query</em>' containment reference.
   * @see #setSubQuery(SubQuery)
   * @see jpaqldsl.jPAQLDsl.JPAQLDslPackage#getStringExpression_SubQuery()
   * @model containment="true"
   * @generated
   */
  SubQuery getSubQuery();

  /**
   * Sets the value of the '{@link jpaqldsl.jPAQLDsl.StringExpression#getSubQuery <em>Sub Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Query</em>' containment reference.
   * @see #getSubQuery()
   * @generated
   */
  void setSubQuery(SubQuery value);

} // StringExpression
