/*
 * generated by Xtext 2.35.0
 */
package de.sebastianbenz.xgherkin.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.sebastianbenz.xgherkin.GherkinRuntimeModule;
import de.sebastianbenz.xgherkin.GherkinStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GherkinIdeSetup extends GherkinStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GherkinRuntimeModule(), new GherkinIdeModule()));
	}
	
}
