/**
 * generated by Xtext 2.35.0
 */
package uniandes.academia.generator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uniandes.academia.generator.ComponentContainer#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see uniandes.academia.generator.GeneratorPackage#getComponentContainer()
 * @model
 * @generated
 */
public interface ComponentContainer extends Component
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uniandes.academia.generator.GeneratorPackage#getComponentContainer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uniandes.academia.generator.ComponentContainer#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ComponentContainer
