/**
 * generated by Xtext 2.35.0
 */
package uniandes.academia.generator;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uniandes.academia.generator.ContainerModule#getExports <em>Exports</em>}</li>
 * </ul>
 *
 * @see uniandes.academia.generator.GeneratorPackage#getContainerModule()
 * @model
 * @generated
 */
public interface ContainerModule extends uniandes.academia.generator.Module
{
  /**
   * Returns the value of the '<em><b>Exports</b></em>' reference list.
   * The list contents are of type {@link uniandes.academia.generator.Component}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exports</em>' reference list.
   * @see uniandes.academia.generator.GeneratorPackage#getContainerModule_Exports()
   * @model
   * @generated
   */
  EList<Component> getExports();

} // ContainerModule
