/*
 * generated by Xtext 2.35.0
 */
package org.eclipse.scout.saml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.scout.saml.parser.antlr.internal.InternalSamlParser;
import org.eclipse.scout.saml.services.SamlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SamlParser extends AbstractAntlrParser {

	@Inject
	private SamlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSamlParser createParser(XtextTokenStream stream) {
		return new InternalSamlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SamlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SamlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
