/**
 * generated by Xtext 2.35.0
 */
package es.unex.quercusseg.graphqlXtext;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.Document#getDefs <em>Defs</em>}</li>
 * </ul>
 *
 * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Defs</b></em>' containment reference list.
   * The list contents are of type {@link es.unex.quercusseg.graphqlXtext.Definition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defs</em>' containment reference list.
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getDocument_Defs()
   * @model containment="true"
   * @generated
   */
  EList<Definition> getDefs();

} // Document
