/**
 * generated by Xtext 2.35.0
 */
package es.unex.quercusseg.graphqlXtext;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getSelection <em>Selection</em>}</li>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getOpType <em>Op Type</em>}</li>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getName <em>Name</em>}</li>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getVarDefinitions <em>Var Definitions</em>}</li>
 * </ul>
 *
 * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getOperationDefinition()
 * @model
 * @generated
 */
public interface OperationDefinition extends Definition
{
  /**
   * Returns the value of the '<em><b>Selection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selection</em>' containment reference.
   * @see #setSelection(SelectionSet)
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getOperationDefinition_Selection()
   * @model containment="true"
   * @generated
   */
  SelectionSet getSelection();

  /**
   * Sets the value of the '{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getSelection <em>Selection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selection</em>' containment reference.
   * @see #getSelection()
   * @generated
   */
  void setSelection(SelectionSet value);

  /**
   * Returns the value of the '<em><b>Op Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op Type</em>' attribute.
   * @see #setOpType(String)
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getOperationDefinition_OpType()
   * @model
   * @generated
   */
  String getOpType();

  /**
   * Sets the value of the '{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getOpType <em>Op Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op Type</em>' attribute.
   * @see #getOpType()
   * @generated
   */
  void setOpType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getOperationDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link es.unex.quercusseg.graphqlXtext.OperationDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Var Definitions</b></em>' containment reference list.
   * The list contents are of type {@link es.unex.quercusseg.graphqlXtext.VariableDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Definitions</em>' containment reference list.
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getOperationDefinition_VarDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<VariableDefinition> getVarDefinitions();

} // OperationDefinition
