/**
 * generated by Xtext 2.35.0
 */
package es.unex.quercusseg.graphqlXtext;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.Selection#getDirectives <em>Directives</em>}</li>
 * </ul>
 *
 * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getSelection()
 * @model
 * @generated
 */
public interface Selection extends EObject
{
  /**
   * Returns the value of the '<em><b>Directives</b></em>' containment reference list.
   * The list contents are of type {@link es.unex.quercusseg.graphqlXtext.Directive}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directives</em>' containment reference list.
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getSelection_Directives()
   * @model containment="true"
   * @generated
   */
  EList<Directive> getDirectives();

} // Selection
