/**
 * generated by Xtext 2.35.0
 */
package es.unex.quercusseg.graphqlXtext;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.Type#getName <em>Name</em>}</li>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.Type#isNotNull <em>Not Null</em>}</li>
 *   <li>{@link es.unex.quercusseg.graphqlXtext.Type#getList <em>List</em>}</li>
 * </ul>
 *
 * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link es.unex.quercusseg.graphqlXtext.Type#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Not Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not Null</em>' attribute.
   * @see #setNotNull(boolean)
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getType_NotNull()
   * @model
   * @generated
   */
  boolean isNotNull();

  /**
   * Sets the value of the '{@link es.unex.quercusseg.graphqlXtext.Type#isNotNull <em>Not Null</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not Null</em>' attribute.
   * @see #isNotNull()
   * @generated
   */
  void setNotNull(boolean value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(ListType)
   * @see es.unex.quercusseg.graphqlXtext.GraphqlXtextPackage#getType_List()
   * @model containment="true"
   * @generated
   */
  ListType getList();

  /**
   * Sets the value of the '{@link es.unex.quercusseg.graphqlXtext.Type#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(ListType value);

} // Type
