/**
 * generated by Xtext 2.35.0
 */
package workflowdsl.workflowDsl.impl;

import org.eclipse.emf.ecore.EClass;

import workflowdsl.workflowDsl.BasicConnector;
import workflowdsl.workflowDsl.WorkflowDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Connector</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BasicConnectorImpl extends ConnectorImpl implements BasicConnector
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicConnectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WorkflowDslPackage.Literals.BASIC_CONNECTOR;
  }

} //BasicConnectorImpl
