/*
 * generated by Xtext 2.35.0
 */
package es.unex.quercusseg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphqlXtextAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/unex/quercusseg/parser/antlr/internal/InternalGraphqlXtext.tokens");
	}
}
