/*
 * generated by Xtext 2.35.0
 */
package es.unex.quercusseg.parser.antlr;

import com.google.inject.Inject;
import es.unex.quercusseg.parser.antlr.internal.InternalGraphqlXtextParser;
import es.unex.quercusseg.services.GraphqlXtextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GraphqlXtextParser extends AbstractAntlrParser {

	@Inject
	private GraphqlXtextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_COMMA", "RULE_COMMENT");
	}
	

	@Override
	protected InternalGraphqlXtextParser createParser(XtextTokenStream stream) {
		return new InternalGraphqlXtextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public GraphqlXtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphqlXtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
